// GENERATED by scripts/sync-spacing.mjs — do not hand-edit.
// Source: AmityUiKitWeb src/v4/styles/global.css (--asc-spacing-*), rem/em → px (base 16).

export const spacing = {
  none: 0,
  xxs1: 2,
  xxs2: 4,
  xxs3: 6,
  s1: 8,
  s2: 12,
  m1: 16,
  m2: 20,
  m3: 24,
  l1: 32,
  l2: 40,
  l3: 48,
  l4: 56,
  xl1: 64,
  xl2: 72,
  xl3: 96,
} as const;

export type SpacingToken = keyof typeof spacing;

/** Spacing value in px for a token name (e.g. sp('s2') === 12). */
export function sp(token: SpacingToken): number {
  return spacing[token];
}
