#!/usr/bin/env node
// port-status.mjs — regenerate scripts/port/STATUS.md: a per-milestone checklist of every
// port unit with its live state (done / stub / todo). Derived from web-parity-map.json +
// the RN tree, so it never drifts. Run after any port work.
//
//   node scripts/port-status.mjs

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { REPO_ROOT, RN, c } from './port/paths.mjs';

const manifest = JSON.parse(readFileSync(resolve(RN.portDir, 'web-parity-map.json'), 'utf8'));
const STUB_RE = /PORT STUB|TODO\(port\)/;

function stateOf(rn, kind) {
  if (!rn) return 'todo';
  const abs = resolve(REPO_ROOT, rn);
  const filePath = kind === 'hooks-only' && existsSync(`${abs}.ts`) ? `${abs}.ts` : abs;
  if (!existsSync(filePath)) return 'todo';
  // collect files, check for stub markers
  const files = [];
  const walk = (p) => {
    if (statSync(p).isFile()) { if (/\.[jt]sx?$/.test(p)) files.push(p); return; }
    for (const n of readdirSync(p)) walk(resolve(p, n));
  };
  walk(filePath);
  if (files.some((f) => STUB_RE.test(readFileSync(f, 'utf8')))) return 'stub';
  return files.length ? 'done' : 'todo';
}

// gather all port units (enumerable + curated), grouped by milestone
const rows = [];
for (const [k, u] of Object.entries(manifest.units)) {
  if (u.status !== 'port') continue;
  rows.push({ ms: u.milestone, key: k, state: stateOf(u.rn, u.kind) });
}
for (const [k, u] of Object.entries(manifest.curated || {})) {
  rows.push({ ms: u.milestone, key: `curated/${k}`, state: stateOf(u.rn, u.kind) });
}

const mark = { done: '[x]', stub: '[~]', todo: '[ ]' };
const byMs = {};
for (const r of rows) (byMs[r.ms] ||= []).push(r);

let md = '# Port status\n\n_Generated by `node scripts/port-status.mjs` — do not hand-edit. `[x]` done · `[~]` stub · `[ ]` todo._\n\n';
let totalDone = 0;
for (const ms of Object.keys(byMs).sort()) {
  const units = byMs[ms].sort((a, b) => a.key.localeCompare(b.key));
  const done = units.filter((u) => u.state === 'done').length;
  totalDone += done;
  md += `## Milestone ${ms} — ${done}/${units.length}\n\n`;
  for (const u of units) md += `- ${mark[u.state]} ${u.key}\n`;
  md += '\n';
}
md = md.replace('\n\n## Milestone', `\n**Total: ${totalDone}/${rows.length}**\n\n## Milestone`);

writeFileSync(resolve(RN.portDir, 'STATUS.md'), md, 'utf8');
console.log(`  ${c.green('✓')} scripts/port/STATUS.md · ${totalDone}/${rows.length} done`);
