#!/usr/bin/env node
// sync-icons.mjs — port the SoT SVG icon set into an RN-consumable registry.
// IDEMPOTENT / re-runnable. RN has no svg-transformer configured, so instead of
// emitting one component per file we generate a single `name -> raw SVG xml` map.
// The default monochrome fill (#292B32) is replaced with the placeholder
// {{FILL}} so <AmityIcon> can tint it via a design token at render time.
//
//   node scripts/sync-icons.mjs [--sot=/path/to/cleverden]
//
// Output: src/core/design/icons/generated/iconRegistry.ts

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, relative, resolve } from 'node:path';
import { SOT, RN, REPO_ROOT, assertSot, c } from './port/paths.mjs';

assertSot();

if (!existsSync(SOT.iconsDir)) {
  console.error(c.red(`  MISSING SoT icons dir: ${SOT.iconsDir}`));
  process.exit(2);
}

const DEFAULT_FILL = /#292B32/gi; // the SoT monochrome glyph fill
const FILL_PLACEHOLDER = '{{FILL}}';

const files = readdirSync(SOT.iconsDir).filter((f) => f.toLowerCase().endsWith('.svg')).sort();

const entries = [];
let tintable = 0;
let multicolor = 0;

for (const file of files) {
  const name = basename(file, '.svg'); // referenced by name, e.g. "plus-r"
  let xml = readFileSync(resolve(SOT.iconsDir, file), 'utf8').trim();
  // Normalize whitespace/newlines so the generated file is stable across runs.
  xml = xml.replace(/\r\n/g, '\n');

  const hadDefault = DEFAULT_FILL.test(xml);
  DEFAULT_FILL.lastIndex = 0;
  if (hadDefault) {
    xml = xml.replace(DEFAULT_FILL, FILL_PLACEHOLDER);
    tintable++;
  } else {
    // multicolor / stroke-only / non-standard fill: kept verbatim, not tinted.
    multicolor++;
  }
  entries.push({ name, xml, tintable: hadDefault });
}

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const body = entries
  .map((e) => `  ${JSON.stringify(e.name)}: \`${esc(e.xml)}\`,`)
  .join('\n');

const header = `// GENERATED by scripts/sync-icons.mjs — do not hand-edit.
// Source: cleverden uikit/assets/icons/ (${entries.length} icons).
// The default fill (#292B32) is replaced with the '{{FILL}}' placeholder so it
// can be tinted via a design token. Multicolor glyphs are stored verbatim.
//
// Usage:
//   import { getIconXml } from '../generated/iconRegistry';
//   const xml = getIconXml('plus-r', theme.color); // fills {{FILL}} with theme.color
//   <SvgXml xml={xml} width={24} height={24} />

export const ICON_FILL_PLACEHOLDER = '{{FILL}}';

export const iconRegistry = {
${body}
} as const;

export type AmityIconName = keyof typeof iconRegistry;

export const AMITY_ICON_COUNT = ${entries.length};

/** Return the raw SVG xml for an icon, with {{FILL}} replaced by \`color\` (default #292B32). */
export function getIconXml(name: AmityIconName, color = '#292B32'): string {
  const xml = iconRegistry[name];
  if (xml == null) throw new Error('[AmityIcon] unknown icon: ' + String(name));
  return xml.split(ICON_FILL_PLACEHOLDER).join(color);
}
`;

mkdirSync(dirname(RN.iconRegistry), { recursive: true });
writeFileSync(RN.iconRegistry, header, 'utf8');

console.log(`  ${c.green('✓')} ${relative(REPO_ROOT, RN.iconRegistry)}`);
console.log(
  `\n${c.bold('Generated')} ${entries.length} icons · ${tintable} tintable · ` +
    `${multicolor} verbatim (multicolor/stroke)\n`
);
