#!/usr/bin/env node
// sync-spacing.mjs — vendor the spacing scale into RN. IDEMPOTENT / re-runnable.
// Source: the web foundations file src/v4/styles/global.css (the --asc-spacing-* custom
// properties the chat CSS actually references) from the LOCAL web checkout. rem/em → px
// (base 16). Cross-checked against the SoT (cleverden /layout/spacing) — warns on drift.
//
//   node scripts/sync-spacing.mjs [--web=/abs/AmityUiKitWeb] [--sot=/path/to/cleverden]
//
// Output: src/core/design/tokens/spacing.ts  ({ none: 0, xxs1: 2, ... } in px)

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { relative } from 'node:path';
import { SOT, RN, REPO_ROOT, WEB_ROOT, webPath, c } from './port/paths.mjs';

const REM_PX = 16;
const GLOBAL_CSS = webPath('src/v4/styles/global.css');

if (!existsSync(GLOBAL_CSS)) {
  console.error(c.red(`  MISSING web foundations file: ${GLOBAL_CSS}\n  (pass --web=/abs/path to AmityUiKitWeb)`));
  process.exit(2);
}

// Parse --asc-spacing-<name>: <num><unit>;  (unit rem|em → ×16 px, px → as-is, unitless 0)
const css = readFileSync(GLOBAL_CSS, 'utf8');
const entries = {};
for (const m of css.matchAll(/--asc-spacing-([a-z0-9]+):\s*(-?[0-9.]+)(rem|em|px)?\s*;/g)) {
  const [, name, num, unit] = m;
  const n = Number(num);
  entries[name] = unit === 'px' || !unit ? n : Math.round(n * REM_PX * 100) / 100;
}

if (Object.keys(entries).length === 0) {
  console.error(c.red('  No --asc-spacing-* tokens found in global.css'));
  process.exit(2);
}

// Soft cross-check vs SoT /layout/spacing (px). Warn (don't fail) on value drift.
let drift = 0;
if (existsSync(SOT.tokensRaw)) {
  try {
    const scale = JSON.parse(readFileSync(SOT.tokensRaw, 'utf8'))?.layout?.spacing || [];
    const sot = {};
    for (const it of scale) if (it?.name != null) sot[String(it.name).toLowerCase().replace(/-/g, '')] = it.px;
    for (const [k, v] of Object.entries(entries)) {
      if (sot[k] != null && sot[k] !== v) {
        if (drift === 0) console.log(c.yellow('  drift vs SoT /layout/spacing:'));
        console.log(c.yellow(`    ${k}: web ${v}px vs SoT ${sot[k]}px`));
        drift++;
      }
    }
  } catch { /* SoT optional */ }
}

const body = Object.entries(entries).map(([k, v]) => `  ${k}: ${v},`).join('\n');
const out = `// GENERATED by scripts/sync-spacing.mjs — do not hand-edit.
// Source: AmityUiKitWeb src/v4/styles/global.css (--asc-spacing-*), rem/em → px (base 16).

export const spacing = {
${body}
} as const;

export type SpacingToken = keyof typeof spacing;

/** Spacing value in px for a token name (e.g. sp('s2') === 12). */
export function sp(token: SpacingToken): number {
  return spacing[token];
}
`;

writeFileSync(RN.spacingTs, out, 'utf8');
console.log(`  ${c.green('✓')} ${relative(REPO_ROOT, RN.spacingTs)}`);
console.log(
  `\n${c.bold('Vendored')} spacing scale · ${Object.keys(entries).length} tokens (px)` +
    (drift ? c.yellow(` · ${drift} drift vs SoT`) : c.dim(' · matches SoT')) +
    '\n'
);
