import { BackHandler } from 'react-native';
import {
  AmityPageRenderer,
  AmityUiKitProvider,
  AmityUiKitSocial,
  AmityUiKitChat,
  ErrorBoundary,
  navigate,
} from './core';
import { useLocale, useString, defaultLocaleMap } from './core/localization';
import {
  AmityStoryTabComponent,
  AmityCreateStoryPage,
  AmityDraftStoryPage,
  AmityViewStoryPage,
  AmitySocialHomePage,
  AmitySocialHomeTopNavigationComponent,
  AmityCommunitySearchResultComponent,
  AmitySocialGlobalSearchPage,
  AmityTopSearchBarComponent,
  AmityEmptyNewsFeedComponent,
  AmityGlobalFeedComponent,
  AmityMyCommunitiesComponent,
  AmityNewsFeedComponent,
  AmityPostContentComponent,
  AmityPostDetailPage,
  AmityPostTargetSelectionPageType,
  AmityCreatePostMenuComponent,
  AmityDetailedMediaAttachmentComponent,
  AmityMediaAttachmentComponent,
  AmityPostCommentComponent,
  AmityPostComposerPage,
  AmityPostEngagementActionsComponent,
  AmityPostTargetSelectionPage,
  AmityReactionListComponent,
  AmityStoryTargetSelectionPage,
  AmityUserSearchResultComponent,
  AmityMyCommunitiesSearchPage,
  AmityExploreComponent,
  AmityAllCategoriesPage,
  AmityCommunitiesByCategoryPage,
  AmityCommunityProfilePage as CommunityProfilePage,
  AmityCreateLivestreamPage,
  AmityLivestreamPostTargetSelectionPage,
  AmityLivestreamTerminatedPage,
  AmityLivestreamPlayerPage,
  AmityPollTargetSelectionPage,
  AmityPollPostComposerPage,
  AmityCommunityFeedComponent,
  AmityCommunityHeaderComponent,
  AmityCommunityImageFeedComponent,
  AmityCommunityVideoFeedComponent,
  AmityThumbnailActionComponent,
  AmityPostEngagementContentComponent,
  AmityPostTargetType,
  AmityCommunitySetupPage,
  AmityCommunityAddCategoryPage,
  AmityCommunityAddMemberPage,
  AmityCommunityPendingRequestPage,
  AmityCommunitySettingPage,
  AmityCommunityMembershipPage,
  AmityCommunityPostPermissionPage,
  AmityCommunityStorySettingPage,
  AmityCommunityNotificationSettingPage,
  AmityCommunityPostsNotificationSettingPage,
  AmityCommunityCommentsNotificationSettingPage,
  AmityCommunityStoriesNotificationSettingPage,
  AmityCommunityLivestreamsNotificationSettingPage,
  AmityCommunityPinnedPostComponent,
  AmityPendingPostListComponent,
  AmityGlobalStoryTabWrapper,
  AmityPostComposerMode,
  AmityStoryTabComponentEnum,
  mediaAttachment,
  PostDetail,
  AmityUserProfilePage,
  AmityEditUserProfilePage,
  AmityUserRelationshipPage,
  AmityBlockedUsersPage,
} from './social';
import {
  AmityChatHomePage,
  AmityChannelCreateConversationPage,
  AmitySelectGroupMemberPage,
  AmityCreateGroupChatPage,
  AmityChatPage,
  AmityGroupChatPage,
  AmityGroupSettingPage,
  AmityEditGroupProfilePage,
  AmityEditGroupNotificationPage,
  AmityEditGroupMemberPermissionsPage,
  AmityGroupNotificationPreferencePage,
  AmityGroupMemberListPage,
  AmityAddGroupMemberPage,
  AmityBannedGroupMemberListPage,
  AmityArchivedChatPage,
  AmitySearchChannelPage,
} from './chat/pages';

// Polyfill for BackHandler compatibility with older libraries like react-native-modalbox
// In React Native 0.65+, BackHandler.removeEventListener was removed
// This polyfill maintains backward compatibility
if (!(BackHandler as any).removeEventListener) {
  const listeners = new Map();
  const originalAddEventListener = BackHandler.addEventListener;

  BackHandler.addEventListener = (eventName, handler) => {
    const subscription = originalAddEventListener(eventName, handler);
    listeners.set(handler, subscription);
    return subscription;
  };

  (BackHandler as any).removeEventListener = (
    _eventName: string,
    handler: () => boolean
  ) => {
    const subscription = listeners.get(handler);
    if (subscription) {
      subscription.remove();
      listeners.delete(handler);
    }
  };
}

export {
  AmityUiKitProvider,
  ErrorBoundary,
  AmityUiKitSocial,
  AmityUiKitChat,
  AmityStoryTabComponent,
  AmityStoryTabComponentEnum,
  AmityCreateStoryPage,
  AmityDraftStoryPage,
  AmityViewStoryPage,
  AmitySocialHomePage,
  AmitySocialHomeTopNavigationComponent,
  AmityCommunitySearchResultComponent,
  AmitySocialGlobalSearchPage,
  AmityTopSearchBarComponent,
  AmityEmptyNewsFeedComponent,
  AmityGlobalFeedComponent,
  AmityMyCommunitiesComponent,
  AmityNewsFeedComponent,
  AmityPostContentComponent,
  AmityPostDetailPage,
  AmityPostTargetSelectionPageType,
  AmityCreatePostMenuComponent,
  AmityDetailedMediaAttachmentComponent,
  AmityMediaAttachmentComponent,
  AmityPostCommentComponent,
  AmityPostComposerPage,
  AmityPostEngagementActionsComponent,
  AmityPostTargetSelectionPage,
  AmityReactionListComponent,
  AmityStoryTargetSelectionPage,
  AmityUserSearchResultComponent,
  AmityMyCommunitiesSearchPage,
  AmityPostComposerMode,
  mediaAttachment,
  AmityExploreComponent,
  AmityPageRenderer,
  PostDetail,
  AmityUserProfilePage,
  AmityEditUserProfilePage,
  AmityUserRelationshipPage,
  AmityBlockedUsersPage,
  AmityAllCategoriesPage,
  AmityCommunitiesByCategoryPage,
  CommunityProfilePage,
  AmityCreateLivestreamPage,
  AmityLivestreamPostTargetSelectionPage,
  AmityLivestreamTerminatedPage,
  AmityLivestreamPlayerPage,
  AmityPollTargetSelectionPage,
  AmityPollPostComposerPage,
  AmityCommunityFeedComponent,
  AmityCommunityHeaderComponent,
  AmityCommunityImageFeedComponent,
  AmityCommunityVideoFeedComponent,
  AmityThumbnailActionComponent,
  AmityPostEngagementContentComponent,
  AmityPostTargetType,
  AmityCommunitySetupPage,
  AmityCommunityAddCategoryPage,
  AmityCommunityAddMemberPage,
  AmityCommunityPendingRequestPage,
  AmityCommunitySettingPage,
  AmityCommunityMembershipPage,
  AmityCommunityPostPermissionPage,
  AmityCommunityStorySettingPage,
  AmityCommunityNotificationSettingPage,
  AmityCommunityPostsNotificationSettingPage,
  AmityCommunityCommentsNotificationSettingPage,
  AmityCommunityStoriesNotificationSettingPage,
  AmityCommunityLivestreamsNotificationSettingPage,
  AmityCommunityPinnedPostComponent,
  AmityPendingPostListComponent,
  AmityGlobalStoryTabWrapper,
  navigate,
  AmityChatHomePage,
  AmityChannelCreateConversationPage,
  AmitySelectGroupMemberPage,
  AmityCreateGroupChatPage,
  AmityChatPage,
  AmityGroupChatPage,
  AmityGroupSettingPage,
  AmityEditGroupProfilePage,
  AmityEditGroupNotificationPage,
  AmityEditGroupMemberPermissionsPage,
  AmityGroupNotificationPreferencePage,
  AmityGroupMemberListPage,
  AmityAddGroupMemberPage,
  AmityBannedGroupMemberListPage,
  AmityArchivedChatPage,
  AmitySearchChannelPage,
  useLocale,
  useString,
  defaultLocaleMap,
};

export type {
  AmitySelectGroupMemberPageProps,
  AmityCreateGroupChatPageProps,
  AmityChatPageProps,
  AmityGroupChatPageProps,
  AmityGroupSettingPageProps,
  AmityEditGroupProfilePageProps,
  AmityEditGroupNotificationPageProps,
  AmityEditGroupMemberPermissionsPageProps,
  AmityGroupNotificationPreferencePageProps,
  AmityGroupMemberListPageProps,
  AmityAddGroupMemberPageProps,
  AmityBannedGroupMemberListPageProps,
} from './chat/pages';

export type { LocaleBundle, LocaleContextValue } from './core/localization';
